"""Verify natural multi-turn operational conversation flow in OpsDoctor.

Scenario tested:
Turn 1: "Show me pending payments"
Turn 2: "Which ones are stuck?"
Turn 3: "Why is the Meridian payment stuck?"
Turn 4: "Check whether this violates any operational policy"
Turn 5: "Escalate it"
"""

import unittest
import uuid
from packages.agent.orchestrator import OpsDoctorOrchestrator
from packages.agent.state import ApprovalStatus


class TestNaturalConversationFlow(unittest.TestCase):
    def test_five_turn_operational_dialogue(self):
        orch = OpsDoctorOrchestrator()
        session_id = f"test-natural-{uuid.uuid4().hex[:6]}"

        # Turn 1: Show me pending payments
        turn1 = orch.run_turn(session_id, "Show me pending payments")
        self.assertIn("Pending Payments Status Overview", turn1.content)
        self.assertIn("STRIPE", turn1.content)
        # Verify NO Jira tools called
        jira_tools_called = [
            a.data.get("tool") for a in turn1.activities
            if a.data and a.data.get("tool", "").startswith("jira")
        ]
        self.assertEqual(len(jira_tools_called), 0, "Turn 1 must not call Jira")
        # Verify trace does not leak chain-of-thought
        for a in turn1.activities:
            self.assertFalse("User asked about" in a.description, "Activity trace must not leak internal thought")

        # Turn 2: Which ones are stuck?
        turn2 = orch.run_turn(session_id, "Which ones are stuck?")
        self.assertIn("Detailed Bottleneck Analysis", turn2.content)
        self.assertTrue("3D Secure" in turn2.content or "requires_action" in turn2.content or "checkout" in turn2.content)

        # Turn 3: Why is the Meridian payment stuck?
        turn3 = orch.run_turn(session_id, "Why is the Meridian payment stuck?")
        self.assertIn("Meridian Tech", turn3.content)
        self.assertIn("Investigation: Meridian Tech Payment", turn3.content)

        # Turn 4: Check whether this violates any operational policy
        turn4 = orch.run_turn(session_id, "Check whether this violates any operational policy")
        self.assertIn("Payment Procedures", turn4.content)
        self.assertIn("Policy Assessment", turn4.content)

        # Turn 5: Escalate it
        turn5 = orch.run_turn(session_id, "Escalate it")
        self.assertEqual(len(turn5.approvals), 1, "Must stage 1 approval request")
        appr = turn5.approvals[0]
        self.assertEqual(appr.system, "jira")
        self.assertEqual(appr.status, ApprovalStatus.PENDING)
        # Check plain text Jira comment formatting (NOT Markdown)
        comment_text = appr.proposed_payload.get("comment_text", "")
        self.assertIn("OpsDoctor Investigation", comment_text)
        self.assertIn("Incident: INC-2026-042", comment_text)
        self.assertIn("Findings:", comment_text)
        self.assertIn("Policy:", comment_text)
        self.assertIn("Assessment:", comment_text)
        self.assertNotIn("*", comment_text, "Jira comment must not contain markdown asterisks")
        self.assertNotIn("_", comment_text, "Jira comment must not contain markdown underscores")
        self.assertNotIn("`", comment_text, "Jira comment must not contain markdown backticks")
        self.assertNotIn("###", comment_text, "Jira comment must not contain markdown headings")
        self.assertIn("Generated by OpsDoctor", comment_text)


if __name__ == "__main__":
    unittest.main()
